OK_FORMAT = True
from tests._loader import _d
test = _d("eJw9jjELwjAQhRVrlU7+hIwVtGgFQZAuDg6uXUVicmLRJrVJEAfB0cKN5//xpxkRfMu7B+/43iN4vVs/3SnGQPESCDuXVUoYVrpQ1tCmjaFxhQVDW/q2uoKbfwiElv5lFmVZxvjexGtelnynD7s8TpPJiM2SyZCN2WL+9SWbwniaRnntIPKIYyElKGowPGtxAkmN454mdO3vJ3YNWFcRtgj7Fngt9VXRcYCBvVUe2pNa+FmWHHfJByPvRwY=")
