OK_FORMAT = True
from tests._loader import _d
test = _d("eJxrYJl6ggECaqdo9LDkJeamTulhLvQyntLDVpCfmVdSPMWbsYetuDSzJLV4SuwUkCrW5MRiKKeHJTk/BagjILG4OLWoRCExrzjeyzjeUMHWVkHJSUlHQen1sjVvu9bomiu8XrPjzYI5b+bOUHg7deub7jVv5rYovO5e8qZ7jsKb5rmvNjS+nbrl9eYtb1p2vJk1RWlKcSLQ1uT8otSUKR09rMWpJaUFU3oYpvRwlKQmFqXkl+dNyeDrYSmpLADazp6Snwx0XsmU0sRSPQAYtlzZ")
