OK_FORMAT = True
from tests._loader import _d
test = _d("eJxrYJl6lpEBDGqnaPSw5CXmpk7pYS70NpjSw1aQn5lXUjzFm6mHrbg0syS1eErsFJAq1uTEYjBHo3ZKD0tyfgpQi39icXFqUYlCcICrs6drcLxbqI+PXnpqiYaST6a5ko5Cda0mhOuopKlga6tgrqMAknkzd4aC4+ulexTezpz6Zu6Ot1NnvGnZ8WbWFKUpxbVTMriINzYKYqwxwtgosox1SsXlWqAM+a5FMxbqWhOEsThcmwoM+uT8otSUKR09rMWpJaUFU3oYpvRwlKQmFqXkl+dNyRDpYSmpLADGAHtKfjIwjkqmlCaW6gEAhZO4Og==")
