OK_FORMAT = True
from tests._loader import _d
test = _d("eJxrYJnqwsgABrVTNHpY8hJzU6f0MBd6G03pYSvIz8wrKZ7izdjDVlyaWZJaPCV2CkgVa3JiMZijUTulhyU5PwWoJS2xuDi1qEShKDUxuSQzPy/e0EAvPbVEQwkskAg0R0lTwdZWoVopRMlKwVBHQckj1QTEqgUyX2+Y8WbuRAVDgzdzZyhAOK/X7Hkzt0Xh7cypb+bueDt1xpuWHW9mTVGaUlw7JYOrJxaXbQVF+SmlyQjLfDLNsVrypnnum5aNOC1JBfo4Ob8oNWVKRw9rcWpJacGUHoYpPRwlqYlFKfnleVMyBHpYSioLgB5nT8lPBgZNyZTSxFI9ANMtjK8=")
